from fastapi import APIRouter

from app.core.config import settings
from app.schemas.legal import TerminosCondicionesRead


router = APIRouter()

TERMINOS_CONDICIONES = [
    "Los presentes Terminos y Condiciones regulan el acceso y uso de Cyanea, una plataforma digital destinada a facilitar la organizacion colaborativa de viajes grupales. Al crear una cuenta, acceder o utilizar Cyanea, el usuario declara haber leido, comprendido y aceptado estos Terminos y Condiciones.",
    "1. Objeto de la plataforma\nCyanea brinda herramientas digitales para organizar viajes grupales, invitar participantes, planificar actividades, registrar gastos, consultar balances estimados, administrar documentos, recibir notificaciones y coordinar informacion entre usuarios. Cyanea actua unicamente como una herramienta tecnologica de organizacion. La plataforma no presta servicios turisticos, financieros, contables, legales, de transporte, alojamiento, seguros, intermediacion comercial ni procesamiento real de pagos.",
    "2. Responsabilidad del usuario\nEl usuario es exclusivamente responsable por la veracidad, exactitud y actualizacion de los datos que ingrese; por el uso que realice de la informacion disponible en la plataforma; por los acuerdos, decisiones, pagos, reembolsos, reservas, contrataciones o compromisos asumidos con otros usuarios o terceros; por la conservacion de sus credenciales de acceso; y por el contenido, documentos, imagenes, gastos, actividades, comentarios o cualquier otra informacion que cargue en Cyanea. Cyanea no verifica ni garantiza la exactitud, integridad, legalidad o conveniencia de la informacion ingresada por los usuarios.",
    "3. Gastos, balances y liquidaciones\nLas funcionalidades de gastos, balances y liquidaciones tienen caracter meramente informativo y organizativo. Cyanea no procesa pagos reales, no custodia fondos, no garantiza cobros o reembolsos, no interviene en transferencias entre usuarios y no asume responsabilidad por deudas, pagos pendientes, desacuerdos economicos o incumplimientos entre participantes. Toda liquidacion generada por la plataforma debe ser revisada y validada por los usuarios antes de realizar cualquier pago o transferencia.",
    "4. Viajes, reservas y servicios de terceros\nCyanea no organiza, vende ni intermedia viajes, pasajes, excursiones, alojamientos, seguros, restaurantes, actividades turisticas ni ningun otro servicio externo. Cualquier contratacion realizada por los usuarios con aerolineas, alojamientos, agencias, prestadores turisticos, plataformas de pago u otros terceros sera responsabilidad exclusiva de los usuarios y se regira por los terminos y condiciones propios de dichos terceros. Cyanea no sera responsable por cancelaciones, demoras, cambios de precio, incumplimientos, accidentes, perdidas, danos, conflictos o cualquier otra consecuencia derivada de servicios contratados fuera de la plataforma.",
    "5. Disponibilidad del servicio\nCyanea podra no estar disponible, total o parcialmente, por tareas de mantenimiento, actualizaciones, fallas tecnicas, problemas de conectividad, fuerza mayor, intervencion de terceros o cualquier otra causa razonable. Cyanea no garantiza disponibilidad ininterrumpida, ausencia de errores ni conservacion permanente de la informacion cargada por los usuarios. No obstante, procurara aplicar medidas razonables para mantener la continuidad y seguridad del servicio.",
    "6. Uso aceptable\nEl usuario se compromete a no utilizar Cyanea para cargar informacion falsa, enganosa, ofensiva, discriminatoria, ilegal o que afecte derechos de terceros; suplantar identidad o acceder a cuentas ajenas; utilizar la plataforma con fines fraudulentos, ilicitos o abusivos; interferir con el funcionamiento tecnico del sistema; cargar archivos maliciosos, virus o contenido que comprometa la seguridad de la plataforma; o vulnerar derechos de propiedad intelectual, privacidad o confidencialidad de terceros. Cyanea podra suspender, limitar o eliminar cuentas o contenidos que infrinjan estos terminos o afecten el funcionamiento, seguridad o finalidad de la plataforma.",
    "7. Datos personales y privacidad\nCyanea tratara los datos personales de los usuarios conforme a la normativa aplicable en materia de proteccion de datos personales, incluyendo la Ley 25.326 de la Republica Argentina. Los datos seran utilizados para permitir el funcionamiento de la plataforma, gestionar cuentas, viajes, invitaciones, notificaciones, preferencias, seguridad y demas funcionalidades propias del servicio. El usuario podra solicitar el acceso, rectificacion, actualizacion o supresion de sus datos personales conforme a la normativa vigente y a los canales que Cyanea ponga a disposicion.",
    "8. Notificaciones\nCyanea podra enviar notificaciones funcionales relacionadas con viajes, invitaciones, gastos, actividades, recordatorios, cambios relevantes o seguridad de la cuenta. El usuario podra configurar sus preferencias de notificacion cuando la plataforma lo permita. Algunas comunicaciones estrictamente necesarias para el funcionamiento o seguridad del servicio podran enviarse aunque el usuario haya desactivado notificaciones opcionales.",
    "9. Contenido cargado por usuarios\nEl usuario conserva la titularidad sobre el contenido que cargue en Cyanea, pero autoriza a la plataforma a almacenarlo, procesarlo y mostrarlo dentro del servicio para permitir el funcionamiento de las funcionalidades colaborativas. El usuario declara contar con los derechos, autorizaciones o permisos necesarios para cargar y compartir dicho contenido. Cyanea no sera responsable por el contenido cargado por los usuarios ni por los danos, reclamos o conflictos que dicho contenido pudiera generar frente a otros usuarios o terceros.",
    "10. Limitacion de responsabilidad\nEn la maxima medida permitida por la normativa aplicable, Cyanea no sera responsable por danos directos, indirectos, incidentales, especiales, consecuenciales, perdida de datos, perdida de oportunidades, perjuicios economicos, conflictos entre usuarios, decisiones de viaje, pagos realizados fuera de la plataforma, incumplimientos de terceros o cualquier consecuencia derivada del uso o imposibilidad de uso del servicio. El usuario reconoce que utiliza Cyanea bajo su propia responsabilidad y criterio. Nada de lo aqui previsto excluira responsabilidades que no puedan ser validamente limitadas conforme a la legislacion aplicable.",
    "11. Baja de cuenta\nEl usuario podra solicitar la baja de su cuenta desde los mecanismos disponibles en la plataforma. Por razones de integridad historica de viajes grupales, Cyanea podra conservar ciertos registros asociados a viajes compartidos, gastos, documentos o actividades, aplicando medidas de anonimizacion o desvinculacion cuando corresponda.",
    "12. Modificaciones\nCyanea podra modificar estos Terminos y Condiciones cuando lo considere necesario, por cambios funcionales, tecnicos, legales o comerciales. Cuando los cambios sean relevantes, Cyanea podra requerir una nueva aceptacion por parte del usuario. La continuidad en el uso de la plataforma luego de la publicacion de cambios implicara aceptacion de la version vigente.",
    "13. Legislacion aplicable\nEstos Terminos y Condiciones se regiran por las leyes de la Republica Argentina. Cualquier controversia derivada del uso de Cyanea sera sometida a la jurisdiccion de los tribunales competentes, salvo que la normativa aplicable establezca otra autoridad o procedimiento obligatorio.",
    "14. Contacto\nPara consultas, solicitudes vinculadas a datos personales, reclamos o comunicaciones relacionadas con estos Terminos y Condiciones, el usuario podra contactar a Cyanea a traves de los canales informados dentro de la aplicacion o sitio oficial.",
]


@router.get("/terms", response_model=TerminosCondicionesRead)
def get_terms() -> TerminosCondicionesRead:
    return TerminosCondicionesRead(
        version=settings.terms_version,
        titulo="Terminos y Condiciones de Cyanea",
        contenido=TERMINOS_CONDICIONES,
    )
