"""create dias cronogramas table"""

revision = '7265c2bf35a9'
down_revision = '0004_email_confirmado'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DiasCronogramas',
    sa.Column('IdDiaCronograma', sa.Integer(), nullable=False),
    sa.Column('IdViaje', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.Date(), nullable=False),
    sa.Column('IndiceDia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IdViaje'], ['Viajes.IdViaje'], name='FK_DiasCronogramas_Viajes_IdViaje', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('IdDiaCronograma')
    )
    op.alter_column('EstadosInvitaciones', 'IdEstadoInvitacion',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1))
    op.drop_index(op.f('UX_EstadosInvitaciones_Nombre'), table_name='EstadosInvitaciones')
    op.create_unique_constraint(None, 'EstadosInvitaciones', ['Nombre'])
    op.alter_column('EstadosParticipaciones', 'IdEstadoParticipacion',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1))
    op.drop_index(op.f('UX_EstadosParticipaciones_Nombre'), table_name='EstadosParticipaciones')
    op.alter_column('EstadosViajes', 'IdEstadoViaje',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1))
    op.drop_index(op.f('UX_EstadosViajes_Nombre'), table_name='EstadosViajes')
    op.drop_index(op.f('IX_Gastos_IdCategoria'), table_name='Gastos')
    op.drop_index(op.f('IX_Gastos_IdPagador'), table_name='Gastos')
    op.drop_index(op.f('IX_Gastos_IdViaje'), table_name='Gastos')
    op.alter_column('InvitacionesViajes', 'IdInvitacionViaje',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('InvitacionesViajes', 'IdViaje',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('InvitacionesViajes', 'IdEstadoInvitacion',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('InvitacionesViajes', 'InvitadoPor',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('InvitacionesViajes', 'IdUsuarioRegistrado',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('IX_InvitacionesViajes_IdEstadoInvitacion'), table_name='InvitacionesViajes')
    op.drop_index(op.f('IX_InvitacionesViajes_IdUsuarioRegistrado'), table_name='InvitacionesViajes')
    op.drop_index(op.f('IX_InvitacionesViajes_IdViaje'), table_name='InvitacionesViajes')
    op.drop_index(op.f('IX_InvitacionesViajes_InvitadoPor'), table_name='InvitacionesViajes')
    op.drop_index(op.f('IX_ParticipantesGastos_IdGasto'), table_name='ParticipantesGastos')
    op.drop_index(op.f('IX_ParticipantesGastos_IdParticipanteViaje'), table_name='ParticipantesGastos')
    op.alter_column('ParticipantesViajes', 'IdParticipanteViaje',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('ParticipantesViajes', 'IdViaje',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('ParticipantesViajes', 'IdUsuario',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('ParticipantesViajes', 'IdRolParticipante',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('ParticipantesViajes', 'IdEstadoParticipacion',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('ParticipantesViajes', 'InvitadoPor',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('IX_ParticipantesViajes_IdEstadoParticipacion'), table_name='ParticipantesViajes')
    op.drop_index(op.f('IX_ParticipantesViajes_IdRolParticipante'), table_name='ParticipantesViajes')
    op.drop_index(op.f('IX_ParticipantesViajes_IdUsuario'), table_name='ParticipantesViajes')
    op.drop_index(op.f('IX_ParticipantesViajes_InvitadoPor'), table_name='ParticipantesViajes')
    op.alter_column('RolesParticipantes', 'IdRolParticipante',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1))
    op.drop_index(op.f('UX_RolesParticipantes_Nombre'), table_name='RolesParticipantes')
    op.alter_column('Usuarios', 'IdUsuario',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('Usuarios', 'HashedPassword',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Usuarios', 'FotoUrl',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('UX_Usuarios_Email'), table_name='Usuarios')
    op.drop_index(op.f('UX_Usuarios_NombreUsuario'), table_name='Usuarios')
    op.alter_column('Viajes', 'IdViaje',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('Viajes', 'Descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Viajes', 'FechaInicio',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('Viajes', 'FechaFin',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('Viajes', 'IdEstadoViaje',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('Viajes', 'IdAdministrador',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('IX_Viajes_IdAdministrador'), table_name='Viajes')
    op.drop_index(op.f('IX_Viajes_IdEstadoViaje'), table_name='Viajes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('IX_Viajes_IdEstadoViaje'), 'Viajes', ['IdEstadoViaje'], unique=False)
    op.create_index(op.f('IX_Viajes_IdAdministrador'), 'Viajes', ['IdAdministrador'], unique=False)
    op.alter_column('Viajes', 'IdAdministrador',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('Viajes', 'IdEstadoViaje',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('Viajes', 'FechaFin',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('Viajes', 'FechaInicio',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('Viajes', 'Descripcion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Viajes', 'IdViaje',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.create_index(op.f('UX_Usuarios_NombreUsuario'), 'Usuarios', ['NombreUsuario'], unique=True)
    op.create_index(op.f('UX_Usuarios_Email'), 'Usuarios', ['Email'], unique=True)
    op.alter_column('Usuarios', 'FotoUrl',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Usuarios', 'HashedPassword',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Usuarios', 'IdUsuario',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.create_index(op.f('UX_RolesParticipantes_Nombre'), 'RolesParticipantes', ['Nombre'], unique=True)
    op.alter_column('RolesParticipantes', 'IdRolParticipante',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1))
    op.create_index(op.f('IX_ParticipantesViajes_InvitadoPor'), 'ParticipantesViajes', ['InvitadoPor'], unique=False)
    op.create_index(op.f('IX_ParticipantesViajes_IdUsuario'), 'ParticipantesViajes', ['IdUsuario'], unique=False)
    op.create_index(op.f('IX_ParticipantesViajes_IdRolParticipante'), 'ParticipantesViajes', ['IdRolParticipante'], unique=False)
    op.create_index(op.f('IX_ParticipantesViajes_IdEstadoParticipacion'), 'ParticipantesViajes', ['IdEstadoParticipacion'], unique=False)
    op.alter_column('ParticipantesViajes', 'InvitadoPor',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('ParticipantesViajes', 'IdEstadoParticipacion',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('ParticipantesViajes', 'IdRolParticipante',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('ParticipantesViajes', 'IdUsuario',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ParticipantesViajes', 'IdViaje',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ParticipantesViajes', 'IdParticipanteViaje',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.create_index(op.f('IX_ParticipantesGastos_IdParticipanteViaje'), 'ParticipantesGastos', ['IdParticipanteViaje'], unique=False)
    op.create_index(op.f('IX_ParticipantesGastos_IdGasto'), 'ParticipantesGastos', ['IdGasto'], unique=False)
    op.create_index(op.f('IX_InvitacionesViajes_InvitadoPor'), 'InvitacionesViajes', ['InvitadoPor'], unique=False)
    op.create_index(op.f('IX_InvitacionesViajes_IdViaje'), 'InvitacionesViajes', ['IdViaje'], unique=False)
    op.create_index(op.f('IX_InvitacionesViajes_IdUsuarioRegistrado'), 'InvitacionesViajes', ['IdUsuarioRegistrado'], unique=False)
    op.create_index(op.f('IX_InvitacionesViajes_IdEstadoInvitacion'), 'InvitacionesViajes', ['IdEstadoInvitacion'], unique=False)
    op.alter_column('InvitacionesViajes', 'IdUsuarioRegistrado',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('InvitacionesViajes', 'InvitadoPor',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('InvitacionesViajes', 'IdEstadoInvitacion',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('InvitacionesViajes', 'IdViaje',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('InvitacionesViajes', 'IdInvitacionViaje',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.create_index(op.f('IX_Gastos_IdViaje'), 'Gastos', ['IdViaje'], unique=False)
    op.create_index(op.f('IX_Gastos_IdPagador'), 'Gastos', ['IdPagador'], unique=False)
    op.create_index(op.f('IX_Gastos_IdCategoria'), 'Gastos', ['IdCategoria'], unique=False)
    op.create_index(op.f('UX_EstadosViajes_Nombre'), 'EstadosViajes', ['Nombre'], unique=True)
    op.alter_column('EstadosViajes', 'IdEstadoViaje',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1))
    op.create_index(op.f('UX_EstadosParticipaciones_Nombre'), 'EstadosParticipaciones', ['Nombre'], unique=True)
    op.alter_column('EstadosParticipaciones', 'IdEstadoParticipacion',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1))
    op.drop_constraint(None, 'EstadosInvitaciones', type_='unique')
    op.create_index(op.f('UX_EstadosInvitaciones_Nombre'), 'EstadosInvitaciones', ['Nombre'], unique=True)
    op.alter_column('EstadosInvitaciones', 'IdEstadoInvitacion',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1))
    op.drop_table('DiasCronogramas')
    # ### end Alembic commands ###
