"""agregar tabla checklists"""

revision = '14dadec61532'
down_revision = 'e3a86acc1846'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CategoriasChecklist',
    sa.Column('IdCategoriaChecklist', sa.BigInteger(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.Column('Activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('IdCategoriaChecklist'),
    sa.UniqueConstraint('Nombre')
    )
    op.create_table('Checklists',
    sa.Column('IdChecklist', sa.Integer(), nullable=False),
    sa.Column('IdViaje', sa.Integer(), nullable=False),
    sa.Column('IdUsuarioCreador', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=60), nullable=False),
    sa.Column('IdCategoriaChecklist', sa.BigInteger(), nullable=False),
    sa.Column('Completada', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('FechaCreacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['IdCategoriaChecklist'], ['CategoriasChecklist.IdCategoriaChecklist'], name='FK_Checklists_CategoriasChecklist'),
    sa.ForeignKeyConstraint(['IdUsuarioCreador'], ['Usuarios.IdUsuario'], name='FK_Checklists_Usuarios_IdUsuario'),
    sa.ForeignKeyConstraint(['IdViaje'], ['Viajes.IdViaje'], name='FK_Checklists_Viajes_IdViaje'),
    sa.PrimaryKeyConstraint('IdChecklist')
    )
    op.create_table('ResponsablesChecklist',
    sa.Column('IdChecklist', sa.Integer(), nullable=False),
    sa.Column('IdUsuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IdChecklist'], ['Checklists.IdChecklist'], name='FK_ResponsablesChecklist_Checklists', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['IdUsuario'], ['Usuarios.IdUsuario'], name='FK_ResponsablesChecklist_Usuarios', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('IdChecklist', 'IdUsuario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ResponsablesChecklist')
    op.drop_table('Checklists')
    op.drop_table('CategoriasChecklist')
    # ### end Alembic commands ###
