"""tablas recuperacion password"""

revision = '4f4ab2082d92'
down_revision = 'b7d4e2a9c1f3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SolicitudesRecuperacionPassword',
    sa.Column('IdSolicitud', sa.Integer(), nullable=False),
    sa.Column('IdUsuario', sa.Integer(), nullable=True),
    sa.Column('EmailHash', sa.String(length=64), nullable=False),
    sa.Column('Ip', sa.String(length=45), nullable=True),
    sa.Column('Tipo', sa.String(length=30), nullable=False),
    sa.Column('Fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['IdUsuario'], ['Usuarios.IdUsuario'], name='FK_SolicitudesRecuperacionPassword_Usuarios_IdUsuario'),
    sa.PrimaryKeyConstraint('IdSolicitud')
    )
    op.create_index(op.f('ix_SolicitudesRecuperacionPassword_EmailHash'), 'SolicitudesRecuperacionPassword', ['EmailHash'], unique=False)
    op.create_index(op.f('ix_SolicitudesRecuperacionPassword_Ip'), 'SolicitudesRecuperacionPassword', ['Ip'], unique=False)
    op.create_table('TokensRecuperacionPassword',
    sa.Column('IdTokenRecuperacion', sa.Integer(), nullable=False),
    sa.Column('IdUsuario', sa.Integer(), nullable=False),
    sa.Column('TokenHash', sa.String(length=64), nullable=False),
    sa.Column('FechaCreacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('FechaExpiracion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('FechaUso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('FechaInvalidacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['IdUsuario'], ['Usuarios.IdUsuario'], name='FK_TokensRecuperacionPassword_Usuarios_IdUsuario'),
    sa.PrimaryKeyConstraint('IdTokenRecuperacion'),
    sa.UniqueConstraint('TokenHash')
    )
    op.create_index(op.f('ix_TokensRecuperacionPassword_IdUsuario'), 'TokensRecuperacionPassword', ['IdUsuario'], unique=False)
    op.drop_index(op.f('IX_TokensPushUsuarios_IdUsuario_Activo'), table_name='TokensPushUsuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('IX_TokensPushUsuarios_IdUsuario_Activo'), 'TokensPushUsuarios', ['IdUsuario', 'Activo'], unique=False)
    op.drop_index(op.f('ix_TokensRecuperacionPassword_IdUsuario'), table_name='TokensRecuperacionPassword')
    op.drop_table('TokensRecuperacionPassword')
    op.drop_index(op.f('ix_SolicitudesRecuperacionPassword_Ip'), table_name='SolicitudesRecuperacionPassword')
    op.drop_index(op.f('ix_SolicitudesRecuperacionPassword_EmailHash'), table_name='SolicitudesRecuperacionPassword')
    op.drop_table('SolicitudesRecuperacionPassword')
    # ### end Alembic commands ###
