"""crear votaciones, propuestas y votos"""

revision = '8382d38ddbfe'
down_revision = 'f2bda3d1364f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Votaciones',
    sa.Column('IdVotacion', sa.BigInteger(), nullable=False),
    sa.Column('IdViaje', sa.BigInteger(), nullable=False),
    sa.Column('Titulo', sa.String(length=150), nullable=False),
    sa.Column('Tipo', sa.Enum('opcion_unica', 'opcion_multiple', name='tipo_votacion_enum'), nullable=False),
    sa.Column('FechaCierre', sa.DateTime(timezone=True), nullable=False),
    sa.Column('IdCreador', sa.BigInteger(), nullable=False),
    sa.Column('FechaCreacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('FechaActualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('TRIM("Titulo") <> \'\'', name='CK_Votaciones_Titulo'),
    sa.ForeignKeyConstraint(['IdCreador'], ['Usuarios.IdUsuario'], name='FK_Votaciones_Usuarios_IdCreador'),
    sa.ForeignKeyConstraint(['IdViaje'], ['Viajes.IdViaje'], name='FK_Votaciones_Viajes_IdViaje'),
    sa.PrimaryKeyConstraint('IdVotacion')
    )
    op.create_table('Propuestas',
    sa.Column('IdPropuesta', sa.BigInteger(), nullable=False),
    sa.Column('IdVotacion', sa.BigInteger(), nullable=False),
    sa.Column('Texto', sa.String(length=255), nullable=False),
    sa.Column('Orden', sa.Integer(), nullable=False),
    sa.CheckConstraint('TRIM("Texto") <> \'\'', name='CK_Propuestas_Texto'),
    sa.ForeignKeyConstraint(['IdVotacion'], ['Votaciones.IdVotacion'], name='FK_Propuestas_Votaciones_IdVotacion', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('IdPropuesta')
    )
    op.create_table('Votos',
    sa.Column('IdVoto', sa.BigInteger(), nullable=False),
    sa.Column('IdUsuario', sa.BigInteger(), nullable=False),
    sa.Column('IdVotacion', sa.BigInteger(), nullable=False),
    sa.Column('IdPropuesta', sa.BigInteger(), nullable=False),
    sa.Column('FechaVoto', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['IdPropuesta'], ['Propuestas.IdPropuesta'], name='FK_Votos_Propuestas_IdPropuesta', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['IdUsuario'], ['Usuarios.IdUsuario'], name='FK_Votos_Usuarios_IdUsuario'),
    sa.ForeignKeyConstraint(['IdVotacion'], ['Votaciones.IdVotacion'], name='FK_Votos_Votaciones_IdVotacion', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('IdVoto'),
    sa.UniqueConstraint('IdUsuario', 'IdVotacion', 'IdPropuesta', name='UQ_Votos_Usuario_Propuesta')
    )
    op.alter_column('ParticipantesGastos', 'IdGasto',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('ParticipantesGastos', 'MontoAsignado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ParticipantesGastos', 'MontoAsignado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('ParticipantesGastos', 'IdGasto',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_table('Votos')
    op.drop_table('Propuestas')
    op.drop_table('Votaciones')
    # ### end Alembic commands ###
