"""add_espublico_to_documentos"""

revision = 'a74611df1e0a'
down_revision = 'f78fb910696e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DocumentosViajes', sa.Column('EsPublico', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DocumentosViajes', 'EsPublico')
    # ### end Alembic commands ###
