"""agregar comprobante a gastos"""

revision = 'acba6c3668f2'
down_revision = '6fa467fa28ec'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gastos', sa.Column('IdDocumentoComprobante', sa.Integer(), nullable=True))
    op.create_foreign_key('FK_Gastos_DocumentosViajes_IdDocumentoComprobante', 'Gastos', 'DocumentosViajes', ['IdDocumentoComprobante'], ['IdDocumento'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK_Gastos_DocumentosViajes_IdDocumentoComprobante', 'Gastos', type_='foreignkey')
    op.drop_column('Gastos', 'IdDocumentoComprobante')
    # ### end Alembic commands ###
